from django.db import models




# drinking water form model
class DrinkingWaterForm(models.Model):
    form_name = "Drinking Water Form"
    id = models.AutoField(primary_key=True)
    lab_report_no = models.CharField(max_length=50)
    invoice_bill_no = models.CharField(max_length=50)
    reporting_date = models.CharField(max_length=50, null=True)
    report_to = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    attention = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    sample_id = models.CharField(max_length=30)
    sample_collection_date = models.CharField(max_length=50, null=True)
    sample_description = models.CharField(max_length=300)
    sample_type = models.CharField(max_length=100)
    sample_collected_by = models.CharField(max_length=100)
    date_of_analysis_from = models.CharField(max_length=50, null=True)
    date_of_analysis_to = models.CharField(max_length=50, null=True)
    test_description = models.CharField(max_length=500)
    select =  models.CharField(max_length=50, null = True )
    water_sr1 =  models.CharField(max_length=50, null = True )
    water_sr2 =  models.CharField(max_length=50, null = True )
    water_sr3 =  models.CharField(max_length=50, null = True )
    water_sr4 =  models.CharField(max_length=50, null = True )
    water_sr5 =  models.CharField(max_length=50, null = True )
    water_sr6 =  models.CharField(max_length=50, null = True )
    water_sr7 =  models.CharField(max_length=50, null = True )
    water_sr8 =  models.CharField(max_length=50, null = True )
    water_sr9 =  models.CharField(max_length=50, null = True )
    water_sr10 =  models.CharField(max_length=50, null = True )
    water_sr11 =  models.CharField(max_length=50, null = True )
    water_sr12 =  models.CharField(max_length=50, null = True )
    water_sr13 =  models.CharField(max_length=50, null = True )
    water_sr14 =  models.CharField(max_length=50, null = True )
    water_sr15 =  models.CharField(max_length=50, null = True )
    water_sr16 =  models.CharField(max_length=50, null = True )
    water_sr17 =  models.CharField(max_length=50, null = True )
    water_sr18 =  models.CharField(max_length=50, null = True )
    water_sr19 =  models.CharField(max_length=50, null = True )
    water_sr20 =  models.CharField(max_length=50, null = True )
    water_sr21 =  models.CharField(max_length=50, null = True )
    water_sr22 =  models.CharField(max_length=50, null = True )
    water_sr23 =  models.CharField(max_length=50, null = True )
    water_sr24 =  models.CharField(max_length=50, null = True )
    water_sr25 =  models.CharField(max_length=50, null = True )
    water_sr26 =  models.CharField(max_length=50, null = True )
    water_sr27 =  models.CharField(max_length=50, null = True )
    water_sr28 =  models.CharField(max_length=50, null = True )
    water_sr29 =  models.CharField(max_length=50, null = True )
    water_sr30 =  models.CharField(max_length=50, null = True )
    water_sr31 =  models.CharField(max_length=50, null = True )
    water_sr32 =  models.CharField(max_length=50, null = True )
    legend_1 = models.CharField(max_length=100, null=True)
    legend_2 = models.CharField(max_length=100, null=True)
    legend_3 = models.CharField(max_length=100, null=True)
    legend_4 = models.CharField(max_length=100, null=True)
    legend_5 = models.CharField(max_length=100, null=True)
    legend_6 = models.CharField(max_length=100, null=True)
    legend_7 = models.CharField(max_length=100, null=True)
    legend_8 = models.CharField(max_length=100, null=True)
    legend_9 = models.CharField(max_length=100, null=True)
    legend_10 = models.CharField(max_length=100, null=True)
    legend_11 = models.CharField(max_length=100, null=True)
    edit_note = models.CharField(max_length=100,null=True)
    custom_legend = models.CharField(max_length=100,null=True)
    doc_controll_1 = models.CharField(max_length=100,null=True)
    doc_controll_2 = models.CharField(max_length=100,null=True)
    doc_controll_3 = models.CharField(max_length=100,null=True)
    analyzed_by = models.ImageField(default="")
    reviewed_by = models.ImageField(default="")
    approved_by = models.ImageField(default="")
    approved_by1 = models.ImageField(default="")
    location =models.CharField(max_length=50,null=True)
    
    

    def __str__(self):
        return self.form_name 

class GaseousEmissionForm(models.Model):
    form_name = "Gaseous Emission Form"
    id = models.AutoField(primary_key=True)
    GasEm_lab_report_no1 = models.CharField(max_length=50)
    GasEm_invoice_bill_no = models.CharField(max_length=50)
    GaseEm_reporting_date = models.CharField(max_length=50, null=True)
    GaseEm_reporting_to = models.CharField(max_length=50)
    GaseEm_address = models.CharField(max_length=100)
    GaseEm_attention = models.CharField(max_length=100)
    GaseEm_email = models.CharField(max_length=100)
    GaseEm_test_id = models.CharField(max_length=30)
    GaseEm_test_perf_date = models.CharField(max_length=40)
    GaseEm_test_type = models.CharField(max_length=300)
    GaseEm_test_perf_by = models.CharField(max_length=100)
    GasEm_test_desc = models.CharField(max_length=100)
    GaseEm_types = models.CharField(max_length=100)
    GaseEm_select = models.CharField(max_length=100,null=True)
    GaseEm_sr1 = models.CharField(max_length=50,null=True)
    GaseEm_sr2 =  models.CharField(max_length=50, null = True )
    GaseEm_sr3 =  models.CharField(max_length=50, null = True )
    GaseEm_sr4 =  models.CharField(max_length=50, null = True )
    GaseEm_sr5 =  models.CharField(max_length=50, null = True )
    GaseEm_sr6 =  models.CharField(max_length=50, null = True )
    GaseEm_sr7 =  models.CharField(max_length=50, null = True )
    GaseEm_sr8 =  models.CharField(max_length=50, null = True )
    GaseEm_sr9 =  models.CharField(max_length=50, null = True )
    GaseEm_sr10 =  models.CharField(max_length=50, null = True )
    GaseEm_sr11 =  models.CharField(max_length=50, null = True )
    GaseEm_sr12 =  models.CharField(max_length=50, null = True )
    GaseEm_sr13 =  models.CharField(max_length=50, null = True )
    GaseEm_sr14 =  models.CharField(max_length=50, null = True )
    GaseEm_sr15 =  models.CharField(max_length=50, null = True )
    GaseEm_sr16 =  models.CharField(max_length=50, null = True )
    GaseEm_sr17 =  models.CharField(max_length=50, null = True )
    GaseEm_sr18 =  models.CharField(max_length=50, null = True )
    GaseEm_sr19 =  models.CharField(max_length=50, null = True )
    GaseEm_sr20 =  models.CharField(max_length=50, null = True )
    GaseEm_sr21 =  models.CharField(max_length=50, null = True )
    GaseEm_sr22 =  models.CharField(max_length=50, null = True )
    GaseEm_legend_1 = models.CharField(max_length=100, null=True)
    GaseEm_legend_2 = models.CharField(max_length=100, null=True)
    GaseEm_legend_3 = models.CharField(max_length=100, null=True)
    GaseEm_legend_4 = models.CharField(max_length=100, null=True)
    GaseEm_legend_5 = models.CharField(max_length=100, null=True)
    GaseEm_legend_6 = models.CharField(max_length=100, null=True)
    GaseEm_legend_7 = models.CharField(max_length=100, null=True)
    GaseEm_legend_8 = models.CharField(max_length=100, null=True)
    GaseEm_legend_9 = models.CharField(max_length=100, null=True)
    GaseEm_legend_10 = models.CharField(max_length=100, null=True)
    GaseEm_legend_11 = models.CharField(max_length=100, null=True)
    GaseEm_edit_note = models.CharField(max_length=500,null=True)
    GaseEm_custom_legend = models.CharField(max_length=100,null=True)
    GaseEm_doc_con_1 = models.CharField(max_length=100,null=True)
    GaseEm_doc_con_2 = models.CharField(max_length=100,null=True)
    GaseEm_doc_con_3 = models.CharField(max_length=100,null=True)
    GaseEm_analyzed_by = models.ImageField(default="")
    GaseEm_reviewd_by = models.ImageField(default="")
    GaseEm_approved_by = models.ImageField(default="")
    GaseEm_approved_by1 = models.ImageField(default="")
    location =models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.form_name 
    
class AmbientAirForm(models.Model):
    form_name = "Ambient Air Form"
    id = models.AutoField(primary_key=True)
    ambienAir_lab_report_no1 = models.CharField(max_length=50)
    ambienAir_invoice_bill_no = models.CharField(max_length=50)
    ambientAir_reporting_date = models.CharField(max_length=50, null=True)
    ambientAir_reporting_to = models.CharField(max_length=50)
    ambientAir_address = models.CharField(max_length=100)
    ambientAir_attention = models.CharField(max_length=100)
    ambientAir_email = models.CharField(max_length=100)
    ambientAir_test_id = models.CharField(max_length=30)
    ambientAir_test_perf_date = models.CharField(max_length=40)
    ambientAir_test_type_location = models.CharField(max_length=300)
    ambientAir_test_perf_by = models.CharField(max_length=100)
    ambienAir_test_desc = models.CharField(max_length=100)
    ambienAir_select = models.CharField(max_length=100,null=True)
    ambientAir_sr1 = models.CharField(max_length=50,null=True)
    ambientAir_sr2 =  models.CharField(max_length=50, null = True )
    ambientAir_sr3 =  models.CharField(max_length=50, null = True )
    ambientAir_sr4 =  models.CharField(max_length=50, null = True )
    ambientAir_sr5 =  models.CharField(max_length=50, null = True )
    ambientAir_sr6 =  models.CharField(max_length=50, null = True )
    ambientAir_sr7 =  models.CharField(max_length=50, null = True )
    ambientAir_sr8 =  models.CharField(max_length=50, null = True )
    ambientAir_sr9 =  models.CharField(max_length=50, null = True )
    ambientAir_sr10 =  models.CharField(max_length=50, null = True )
    ambientAir_sr11 =  models.CharField(max_length=50, null = True )
    ambientAir_sr12 =  models.CharField(max_length=50, null = True )
    ambientAir_sr13 =  models.CharField(max_length=50, null = True )
    ambientAir_sr14 =  models.CharField(max_length=50, null = True )
    ambientAir_legend_1 = models.CharField(max_length=100, null=True)
    ambientAir_legend_2 = models.CharField(max_length=100, null=True)
    ambientAir_legend_3 = models.CharField(max_length=100, null=True)
    ambientAir_legend_4 = models.CharField(max_length=100, null=True)
    ambientAir_legend_5 = models.CharField(max_length=100, null=True)
    ambientAir_legend_6 = models.CharField(max_length=100, null=True)
    ambientAir_edit_note = models.CharField(max_length=100,null=True)
    ambientAir_custom_legend = models.CharField(max_length=100,null=True)
    ambientAir_doc_con_1 = models.CharField(max_length=100,null=True)
    ambientAir_doc_con_2 = models.CharField(max_length=100,null=True)
    ambientAir_doc_con_3 = models.CharField(max_length=100,null=True)
    ambientAir_analyzed_by = models.ImageField(default="")
    ambientAir_reviewd_by = models.ImageField(default="")
    ambientAir_approved_by = models.ImageField(default="")
    ambientAir_approved_by1 = models.ImageField(default="",null=True)
    location =models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.form_name     
    

class WasteWaterSludge(models.Model):
     form_name = "Waste Water Sludge Form"
     id = models.AutoField(primary_key=True)
     ww_lab_report_no = models.CharField(max_length=50)
     ww_invoice_no = models.CharField(max_length=50)
     ww_report_date = models.CharField(max_length=50)
     ww_report_to = models.CharField(max_length=50)
     ww_address = models.CharField(max_length=50)
     ww_attention = models.CharField(max_length=50)
     ww_email = models.CharField(max_length=50)
     ww_sampleid = models.CharField(max_length=50)
     ww_sample_colec_Date = models.CharField(max_length=50)
     ww_sample_desc = models.CharField(max_length=50)
     ww_sample_type = models.CharField(max_length=50)
     ww_sample_colec_by = models.CharField(max_length=50)
     ww_date_of_analy = models.CharField(max_length=50)
     ww_test_desc = models.CharField(max_length=50)
     ww_sr1 = models.CharField(max_length=50)
     ww_sr2 = models.CharField(max_length=50)
     ww_sr3 = models.CharField(max_length=50)
     ww_sr4 = models.CharField(max_length=50)
     ww_sr5 = models.CharField(max_length=50)
     ww_sr6 = models.CharField(max_length=50)
     ww_sr7 = models.CharField(max_length=50)
     ww_sr8 = models.CharField(max_length=50)
     ww_sr9 = models.CharField(max_length=50)
     ww_sr10 = models.CharField(max_length=50)
     ww_sr11 = models.CharField(max_length=50)
     ww_sr12 = models.CharField(max_length=50)
     ww_sr13 = models.CharField(max_length=50)
     ww_legend_1 = models.CharField(max_length=50)
     ww_legend_2 = models.CharField(max_length=50)
     ww_legend_3 = models.CharField(max_length=50)
     ww_legend_4 = models.CharField(max_length=50)
     ww_legend_5 = models.CharField(max_length=50)
     ww_legend_6 = models.CharField(max_length=50)
     ww_legend_7 = models.CharField(max_length=50)
     ww_legend_8 = models.CharField(max_length=50)
     ww_legend_9 = models.CharField(max_length=50)
     ww_legend_10 = models.CharField(max_length=50)
     ww_legend_11 = models.CharField(max_length=50)
     ww_editnote = models.CharField(max_length=50)
     ww_custom_legend = models.CharField(max_length=50)
     ww_doc_con_1 = models.CharField(max_length=50)
     ww_doc_con_2 = models.CharField(max_length=50)
     ww_doc_con_3 = models.CharField(max_length=50)
     ww_analyzed_by = models.ImageField(default="")
     ww_reviewd_by = models.ImageField(default="")
     ww_approved_by = models.ImageField(default="")     
     ww_approved_by1 = models.ImageField(default="", null=True)     
     location =models.CharField(max_length=50,null=True)

     def __str__(self):
        return self.form_name 
     



class VehiculEmissionForm(models.Model):
    form_name = "Vehicular Emission Form"
    id = models.AutoField(primary_key=True)
    vehEm_lab_report_no = models.CharField(max_length=50)
    vehEm_invoice_no = models.CharField(max_length=50)
    vehEm_report_date = models.CharField(max_length=50)
    vehEm_report_to = models.CharField(max_length=50,null=True)
    vehEm_address = models.CharField(max_length=50)
    vehEm_attention = models.CharField(max_length=50)
    vehEm_email = models.CharField(max_length=50)
    vehEm_testId = models.CharField(max_length=50)
    vehEm_test_perf_date = models.CharField(max_length=50)
    vehEm_test_type = models.CharField(max_length=50)
    vehEm_test_perfBy = models.CharField(max_length=50)
    vehEm_test_desc = models.CharField(max_length=50)
    select = models.CharField(max_length=50,null=True)
    vehEm_sr1 = models.CharField(max_length=50)
    vehEm_sr2 = models.CharField(max_length=50)
    vehEm_sr3 = models.CharField(max_length=50)
    vehEm_legend_1 = models.CharField(max_length=50)
    vehEm_legend_2 = models.CharField(max_length=50)
    vehEm_legend_3 = models.CharField(max_length=50)
    vehEm_legend_4 = models.CharField(max_length=50)
    vehEm_legend_5 = models.CharField(max_length=50)
    vehEm_legend_6 = models.CharField(max_length=50)
    vehEm_legend_7 = models.CharField(max_length=50)
    vehEm_legend_8 = models.CharField(max_length=50)
    vehEm_legend_9 = models.CharField(max_length=50)
    vehEm_legend_10 = models.CharField(max_length=50)
    vehEm_legend_11 = models.CharField(max_length=50)
    vehEm_edit_note = models.CharField(max_length=50,null=True)
    vehEm_custom_legend = models.CharField(max_length=50)
    vehEm_doc_con1 = models.CharField(max_length=50)
    vehEm_doc_con2 = models.CharField(max_length=50)
    vehEm_doc_con3 = models.CharField(max_length=50)
    vehEm_analyzedby = models.ImageField(default="")
    vehEm_reviewedby = models.ImageField(default="")
    vehEm_approvedby = models.ImageField(default="")
    vehEm_approvedby1 = models.ImageField(default="",null=True)
    location =models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.form_name 
    


class LuxAnalysisForm(models.Model):
        form_name = "Lux Analysis Form"
        id = models.AutoField(primary_key=True)
        lux_lab_report_no = models.CharField(max_length=50)
        lux_invoice_no = models.CharField(max_length=50)
        lux_report_date = models.CharField(max_length=50)
        lux_report_to = models.CharField(max_length=50)
        lux_address = models.CharField(max_length=50)
        lux_attention = models.CharField(max_length=50)
        lux_email = models.CharField(max_length=50)
        lux_testId = models.CharField(max_length=50)
        lux_test_perf_date = models.CharField(max_length=50)
        lux_test_type = models.CharField(max_length=50)
        lux_test_perfBy = models.CharField(max_length=50)
        lux_test_desc = models.CharField(max_length=50)
        lux_parameters_1 = models.CharField(max_length=50)
        lux_result_1 = models.CharField(max_length=50)
        lux_parameters_2 = models.CharField(max_length=50)
        lux_result_2 = models.CharField(max_length=50)
        lux_parameters_3 = models.CharField(max_length=50)
        lux_result_3 = models.CharField(max_length=50)
        lux_parameters_4 = models.CharField(max_length=50)
        lux_result_4 = models.CharField(max_length=50)
        lux_parameters_5 = models.CharField(max_length=50)
        lux_result_5 = models.CharField(max_length=50)
        lux_parameters_6 = models.CharField(max_length=50)
        lux_result_6 = models.CharField(max_length=50)
        lux_parameters_7 = models.CharField(max_length=50)
        lux_result_7 = models.CharField(max_length=50)
        lux_parameters_8 = models.CharField(max_length=50)
        lux_result_8 = models.CharField(max_length=50)
        lux_parameters_9 = models.CharField(max_length=50)
        lux_result_9 = models.CharField(max_length=50)
        lux_parameters_10 = models.CharField(max_length=50)
        lux_result_10 = models.CharField(max_length=50)
        lux_parameters_11 = models.CharField(max_length=50)
        lux_result_11 = models.CharField(max_length=50)
        lux_parameters_12 = models.CharField(max_length=50)
        lux_result_12 = models.CharField(max_length=50)
        lux_parameters_13 = models.CharField(max_length=50)
        lux_result_13 = models.CharField(max_length=50)
        lux_legend_1 = models.CharField(max_length=50,null=True)
        lux_legend_2 = models.CharField(max_length=50,null=True)
        lux_legend_3 = models.CharField(max_length=50,null=True)
        lux_legend_4 = models.CharField(max_length=50,null=True)
        lux_legend_5 = models.CharField(max_length=50,null=True)
        lux_legend_6 = models.CharField(max_length=50,null=True)
        lux_legend_7 = models.CharField(max_length=50,null=True)
        lux_legend_8 = models.CharField(max_length=50,null=True)
        lux_legend_9 = models.CharField(max_length=50,null=True)
        lux_legend_10 = models.CharField(max_length=50,null=True)
        lux_legend_11 = models.CharField(max_length=50,null=True)
        lux_edit_note = models.CharField(max_length=50,null=True)
        lux_custom_legend = models.CharField(max_length=50)
        lux_doc_con1 = models.CharField(max_length=50)
        lux_doc_con2 = models.CharField(max_length=50)
        lux_doc_con3 = models.CharField(max_length=50)
        lux_analyzedby = models.ImageField(default="")
        lux_reviewedby = models.ImageField(default="")
        lux_approvedby = models.ImageField(default="")
        lux_approvedby1 = models.ImageField(default="",null=True)
        location =models.CharField(max_length=50,null=True)



        def __str__(self):
            return self.form_name 
    

class PackingPolyBagForm(models.Model):
    form_name ="Packing Poly Bag"
    id = models.AutoField(primary_key=True)
    pack_lab_rep_no = models.CharField(max_length=50)
    pack_invoice = models.CharField(max_length=50)
    pack_rep_date = models.CharField(max_length=50)
    pack_rep_to = models.CharField(max_length=50)
    pack_address = models.CharField(max_length=50)
    pack_attention = models.CharField(max_length=50)
    pack_email = models.CharField(max_length=50)
    pack_sampleId = models.CharField(max_length=50)
    pack_sample_colc_date = models.CharField(max_length=50)
    pack_sample_desc = models.CharField(max_length=50)
    pack_sample_type = models.CharField(max_length=50)
    pack_sample_colc_by = models.CharField(max_length=50)
    pack_test_desc = models.CharField(max_length=50)
    pack_sr1 = models.CharField(max_length=50)
    pack_legend_1 = models.CharField(max_length=50)
    pack_edit_note = models.CharField(max_length=50)
    pack_custom_legend = models.CharField(max_length=50)
    doc_con1 = models.CharField(max_length=50)
    doc_con2 = models.CharField(max_length=50)
    doc_con3 = models.CharField(max_length=50)
    pack_analyzed_by = models.ImageField(default="")
    pack_reviewed_by = models.ImageField(default="")
    pack_approved_by = models.ImageField(default="")
    pack_approved_by1 = models.ImageField(default="",null=True)
    location =models.CharField(max_length=50,null=True)


    def __str__(self):
        return self.form_name 
    

class MachineOilForm(models.Model):
    form_name = "Machine Oil Form"
    id = models.AutoField(primary_key=True)
    machine_lab_rep_no = models.CharField(max_length=50)
    machine_invoice_no = models.CharField(max_length=50)
    machine_rep_date = models.CharField(max_length=50)
    machine_report_to = models.CharField(max_length=50)
    machine_address = models.CharField(max_length=50)
    machine_attention = models.CharField(max_length=50)
    machine_email = models.CharField(max_length=50)
    machine_sampleId = models.CharField(max_length=50)
    machine_sample_col_date = models.CharField(max_length=50)
    machine_sample_desc = models.CharField(max_length=50)
    machine_sample_type = models.CharField(max_length=50)
    machine_sample_col_by = models.CharField(max_length=50)
    machine_test_desc = models.CharField(max_length=50)
    machine_sr1 = models.CharField(max_length=50)
    machine_sr2 = models.CharField(max_length=50)
    machine_sr3 = models.CharField(max_length=50)
    machine_sr4 = models.CharField(max_length=50)
    machine_sr5 = models.CharField(max_length=50)
    machine_sr6 = models.CharField(max_length=50)
    machine_sr7 = models.CharField(max_length=50)
    machine_sr8 = models.CharField(max_length=50)
    machine_sr9 = models.CharField(max_length=50)
    machine_sr10 = models.CharField(max_length=50)
    machine_sr11 = models.CharField(max_length=50)
    machine_sr12 = models.CharField(max_length=50)
    machine_sr13 = models.CharField(max_length=50)
    machine_sr14 = models.CharField(max_length=50)
    machine_sr15 = models.CharField(max_length=50)
    machine_sr16 = models.CharField(max_length=50)
    machine_legend_1 = models.CharField(max_length=50)
    machine_legend_2 = models.CharField(max_length=50)
    custom_legend = models.CharField(max_length=50,null=True)    
    machine_edit_note = models.CharField(max_length=50)
    machine_custom_legend = models.CharField(max_length=50)
    machine_doc1 = models.CharField(max_length=50)
    machine_doc2 = models.CharField(max_length=50)
    machine_doc3 = models.CharField(max_length=50)
    machine_analyzedby = models.ImageField(max_length=50)
    machine_reviewedby = models.ImageField(max_length=50)
    machine_approvedby = models.ImageField(max_length=50)    
    machine_approvedby1 = models.ImageField(max_length=50,null=True)  
    location =models.CharField(max_length=50,null=True)  
        


    def __str__(self):
        return self.form_name     
    


class MicrobialAnalysis(models.Model):
    form_name = "Microbial Analysis Form"    
    id = models.AutoField(primary_key=True)
    micro_lab_report_no = models.CharField(max_length=150)
    micro_invoice_bill = models.CharField(max_length=150)
    micro_rep_date = models.CharField(max_length=150)
    micro_rep_to = models.CharField(max_length=150)
    micro_address = models.CharField(max_length=150)
    micro_attention = models.CharField(max_length=150)
    micro_email = models.CharField(max_length=150)
    micro_sampleId = models.CharField(max_length=150)
    micro_sample_col_date = models.CharField(max_length=150)
    micro_sample_desc = models.CharField(max_length=150)
    micro_sample_type = models.CharField(max_length=150)
    micro_sample_col_by = models.CharField(max_length=150)
    micro_date_analysis = models.CharField(max_length=150)
    micro_test_desc = models.CharField(max_length=150)
    micro_sr1 = models.CharField(max_length=150)
    micro_sr2 = models.CharField(max_length=150)
    micro_sr3 = models.CharField(max_length=150)
    micro_sr4 = models.CharField(max_length=150)
    micro_sr5 = models.CharField(max_length=150)
    micro_sr6 = models.CharField(max_length=150)
    micro_legend_1 = models.CharField(max_length=150)
    micro_legend_2 = models.CharField(max_length=150)
    micro_editnote = models.CharField(max_length=250)
    micro_custom_legend = models.CharField(max_length=150)
    micro_doc1 = models.CharField(max_length=150)
    micro_doc2 = models.CharField(max_length=150)
    micro_doc3 = models.CharField(max_length=150)
    micro_analyzedby = models.ImageField(default="")
    micro_reviewedby = models.ImageField(default="")
    micro_approvedby = models.ImageField(default="")
    micro_approvedby1 = models.ImageField(default="",null=True)
    location =models.CharField(max_length=50,null=True)


    def __str__(self):
        return self.form_name  
    

class ViscousLiquid(models.Model):
    form_name="Viscous Liquid Form"
    id = models.AutoField(primary_key=True)
    lab_rep_no = models.CharField(max_length=350)
    invoice_no = models.CharField(max_length=350)
    report_date = models.CharField(max_length=350)
    report_to = models.CharField(max_length=350)
    address = models.CharField(max_length=350)
    Attention = models.CharField(max_length=350)
    Email = models.CharField(max_length=350)
    sampleId = models.CharField(max_length=350)
    sample_Col_date = models.CharField(max_length=350)
    sample_Desc = models.CharField(max_length=350)
    sample_type = models.CharField(max_length=350)
    sample_col_by = models.CharField(max_length=350)
    date_of_analysis = models.CharField(max_length=350)
    test_desc = models.CharField(max_length=350)
    viscous_select = models.CharField(max_length=350)
    sr1 = models.CharField(max_length=350)
    legend_1 = models.CharField(max_length=350)
    legend_2 = models.CharField(max_length=350)
    edit_note = models.CharField(max_length=350)
    custom_legend = models.CharField(max_length=350)
    doc1 = models.CharField(max_length=350)
    doc2 = models.CharField(max_length=350)
    doc3 = models.CharField(max_length=350)
    analyzedby = models.ImageField(max_length=350)
    reviewedby = models.ImageField(max_length=350)
    approvedby = models.ImageField(max_length=350)
    approvedby1 = models.ImageField(max_length=350,null=True)
    location =models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.form_name +"-"+ self.lab_rep_no

class AmbientAir2(models.Model):
    form_name= "Ambient Air Quality 2 Form"
    id = models.AutoField(primary_key=True)
    lab_rep_no = models.CharField(max_length=350)
    invoice_no = models.CharField(max_length=350)
    report_date = models.CharField(max_length=350)
    report_to = models.CharField(max_length=350)
    address = models.CharField(max_length=350)
    attention = models.CharField(max_length=350)
    email = models.CharField(max_length=350)
    testId = models.CharField(max_length=350)
    test_perf_date = models.CharField(max_length=350)
    test_type = models.CharField(max_length=350)
    test_desc = models.CharField(max_length=350)
    test_test_perf_by = models.CharField(max_length=350)
    sr1_1 = models.CharField(max_length=350)
    sr1_2 = models.CharField(max_length=350)
    sr1_3 = models.CharField(max_length=350)
    sr1_4 = models.CharField(max_length=350)
    sr1_5 = models.CharField(max_length=350)
    sr1_6 = models.CharField(max_length=350)
    sr1_7 = models.CharField(max_length=350)
    sr1_8 = models.CharField(max_length=350,null=True)
    sr1_9 = models.CharField(max_length=350)
    sr1_10 = models.CharField(max_length=350)
    sr2_0 = models.CharField(max_length=350)
    sr2_1 = models.CharField(max_length=350)
    sr2_2 = models.CharField(max_length=350)
    sr2_3 = models.CharField(max_length=350)
    sr2_4 = models.CharField(max_length=350)
    sr2_5 = models.CharField(max_length=350)
    sr2_6 = models.CharField(max_length=350)
    sr2_7 = models.CharField(max_length=350)
    sr2_8 = models.CharField(max_length=350)
    sr2_9 = models.CharField(max_length=350)
    sr3_0 = models.CharField(max_length=350)
    sr3_1 = models.CharField(max_length=350)
    sr3_2 = models.CharField(max_length=350)
    sr3_3 = models.CharField(max_length=350)
    sr3_4 = models.CharField(max_length=350)
    sr3_5 = models.CharField(max_length=350)
    sr3_6 = models.CharField(max_length=350)
    sr3_7 = models.CharField(max_length=350)
    sr3_8 = models.CharField(max_length=350)
    sr3_9 = models.CharField(max_length=350)
    sr4_0 = models.CharField(max_length=350)
    sr4_1 = models.CharField(max_length=350)
    sr4_2 = models.CharField(max_length=350)
    sr4_3 = models.CharField(max_length=350)
    sr4_4 = models.CharField(max_length=350)
    sr4_5 = models.CharField(max_length=350)
    sr4_6 = models.CharField(max_length=350)
    sr4_7 = models.CharField(max_length=350)
    sr4_8 = models.CharField(max_length=350)
    sr4_9 = models.CharField(max_length=350)
    sr5_0 = models.CharField(max_length=350)
    sr5_1 = models.CharField(max_length=350)
    sr5_2 = models.CharField(max_length=350)
    sr5_3 = models.CharField(max_length=350)
    sr5_4 = models.CharField(max_length=350)
    sr5_5 = models.CharField(max_length=350)
    sr5_6 = models.CharField(max_length=350)
    sr5_7 = models.CharField(max_length=350)
    sr5_8 = models.CharField(max_length=350)
    sr5_9 = models.CharField(max_length=350)
    sr6_0 = models.CharField(max_length=350)
    sr6_1 = models.CharField(max_length=350)
    sr6_2 = models.CharField(max_length=350)
    sr6_3 = models.CharField(max_length=350)
    sr6_4 = models.CharField(max_length=350)
    sr6_5 = models.CharField(max_length=350)
    sr6_6 = models.CharField(max_length=350)
    sr6_7 = models.CharField(max_length=350)
    sr6_8 = models.CharField(max_length=350)
    sr6_9 = models.CharField(max_length=350)
    sr7_0 = models.CharField(max_length=350)
    sr7_1 = models.CharField(max_length=350)
    sr7_2 = models.CharField(max_length=350)
    sr7_3 = models.CharField(max_length=350)
    sr7_4 = models.CharField(max_length=350)
    sr7_5 = models.CharField(max_length=350)
    sr7_6 = models.CharField(max_length=350)
    sr7_7 = models.CharField(max_length=350)
    sr7_8 = models.CharField(max_length=350)
    sr7_9 = models.CharField(max_length=350)
    sr8_0 = models.CharField(max_length=350)
    sr8_1 = models.CharField(max_length=350)
    sr8_2 = models.CharField(max_length=350)
    sr8_3 = models.CharField(max_length=350)
    sr8_4 = models.CharField(max_length=350)
    sr8_5 = models.CharField(max_length=350)
    sr8_6 = models.CharField(max_length=350)
    sr8_7 = models.CharField(max_length=350)
    sr8_8 = models.CharField(max_length=350)
    sr8_9 = models.CharField(max_length=350)
    sr9_0 = models.CharField(max_length=350)
    sr9_1 = models.CharField(max_length=350)
    sr9_2 = models.CharField(max_length=350)
    sr9_3 = models.CharField(max_length=350)
    sr9_4 = models.CharField(max_length=350)
    sr9_5 = models.CharField(max_length=350)
    sr9_6 = models.CharField(max_length=350)
    sr9_7 = models.CharField(max_length=350)
    sr9_8 = models.CharField(max_length=350)
    sr9_9 = models.CharField(max_length=350)
    sr10_0 = models.CharField(max_length=350)
    sr10_1 = models.CharField(max_length=350)
    sr10_2 = models.CharField(max_length=350)
    sr10_3 = models.CharField(max_length=350)
    sr10_4 = models.CharField(max_length=350)
    sr10_5 = models.CharField(max_length=350)
    sr10_6 = models.CharField(max_length=350)
    sr10_7 = models.CharField(max_length=350)
    sr10_8 = models.CharField(max_length=350)
    sr10_9 = models.CharField(max_length=350)
    sr11_0 = models.CharField(max_length=350)
    sr11_1 = models.CharField(max_length=350)
    sr11_2 = models.CharField(max_length=350)
    sr11_3 = models.CharField(max_length=350)
    sr11_4 = models.CharField(max_length=350)
    sr11_5 = models.CharField(max_length=350)
    sr11_6 = models.CharField(max_length=350)
    sr11_7 = models.CharField(max_length=350)
    sr11_8 = models.CharField(max_length=350)
    sr11_9 = models.CharField(max_length=350)
    sr12_0 = models.CharField(max_length=350)
    sr12_1 = models.CharField(max_length=350)
    sr12_2 = models.CharField(max_length=350)
    sr12_3 = models.CharField(max_length=350)
    sr12_4 = models.CharField(max_length=350)
    sr12_5 = models.CharField(max_length=350)
    sr12_6 = models.CharField(max_length=350)
    sr12_7 = models.CharField(max_length=350)
    sr12_8 = models.CharField(max_length=350)
    sr12_9 = models.CharField(max_length=350)
    sr13_0 = models.CharField(max_length=350)
    sr13_1 = models.CharField(max_length=350)
    sr13_2 = models.CharField(max_length=350)
    sr13_3 = models.CharField(max_length=350)
    sr13_4 = models.CharField(max_length=350)
    sr13_5 = models.CharField(max_length=350)
    sr13_6 = models.CharField(max_length=350)
    sr13_7 = models.CharField(max_length=350)
    sr13_8 = models.CharField(max_length=350)
    sr13_9 = models.CharField(max_length=350)
    sr14_0 = models.CharField(max_length=350)
    sr14_1 = models.CharField(max_length=350)
    sr14_2 = models.CharField(max_length=350)
    sr14_3 = models.CharField(max_length=350)
    sr14_4 = models.CharField(max_length=350)
    sr14_5 = models.CharField(max_length=350)
    sr14_6 = models.CharField(max_length=350)
    sr14_7 = models.CharField(max_length=350)
    sr14_8 = models.CharField(max_length=350)
    sr14_9 = models.CharField(max_length=350)
    sr15_0 = models.CharField(max_length=350)
    sr15_1 = models.CharField(max_length=350)
    sr15_2 = models.CharField(max_length=350)
    sr15_3 = models.CharField(max_length=350)
    sr15_4 = models.CharField(max_length=350)
    sr15_5 = models.CharField(max_length=350)
    sr15_6 = models.CharField(max_length=350)
    sr15_7 = models.CharField(max_length=350)
    sr15_8 = models.CharField(max_length=350)
    sr15_9 = models.CharField(max_length=350)
    sr16_0 = models.CharField(max_length=350)
    sr16_1 = models.CharField(max_length=350)
    sr16_2 = models.CharField(max_length=350)
    sr16_3 = models.CharField(max_length=350)
    sr16_4 = models.CharField(max_length=350)
    sr16_5 = models.CharField(max_length=350)
    sr16_6 = models.CharField(max_length=350)
    sr16_7 = models.CharField(max_length=350)
    sr16_8 = models.CharField(max_length=350)
    sr16_9 = models.CharField(max_length=350)
    sr17_0 = models.CharField(max_length=350)
    sr17_1 = models.CharField(max_length=350)
    sr17_2 = models.CharField(max_length=350)
    sr17_3 = models.CharField(max_length=350,null=True)
    sr17_4 = models.CharField(max_length=350)
    sr17_5 = models.CharField(max_length=350)
    sr17_6 = models.CharField(max_length=350)
    sr17_7 = models.CharField(max_length=350)
    sr17_8 = models.CharField(max_length=350)
    sr17_9 = models.CharField(max_length=350)
    sr18_0 = models.CharField(max_length=350)
    sr18_1 = models.CharField(max_length=350)
    sr18_2 = models.CharField(max_length=350)
    sr18_3 = models.CharField(max_length=350)
    sr18_4 = models.CharField(max_length=350)
    sr18_5 = models.CharField(max_length=350)
    sr18_6 = models.CharField(max_length=350)
    sr18_7 = models.CharField(max_length=350)
    sr18_8 = models.CharField(max_length=350)
    sr18_9 = models.CharField(max_length=350)
    sr19_0 = models.CharField(max_length=350)
    sr19_1 = models.CharField(max_length=350)
    sr19_2 = models.CharField(max_length=350)
    sr19_3 = models.CharField(max_length=350)
    sr19_4 = models.CharField(max_length=350)
    sr19_5 = models.CharField(max_length=350)
    sr19_6 = models.CharField(max_length=350)
    sr19_7 = models.CharField(max_length=350)
    sr19_8 = models.CharField(max_length=350)
    sr19_9 = models.CharField(max_length=350)
    sr20_0 = models.CharField(max_length=350)
    sr20_1 = models.CharField(max_length=350)
    sr20_2 = models.CharField(max_length=350)
    sr20_3 = models.CharField(max_length=350)
    sr20_4 = models.CharField(max_length=350)
    sr20_5 = models.CharField(max_length=350)
    sr20_6 = models.CharField(max_length=350)
    sr20_7 = models.CharField(max_length=350)
    sr20_8 = models.CharField(max_length=350)
    sr20_9 = models.CharField(max_length=350)
    sr21_0 = models.CharField(max_length=350)
    sr21_1 = models.CharField(max_length=350)
    sr21_2 = models.CharField(max_length=350)
    sr21_3 = models.CharField(max_length=350)
    sr21_4 = models.CharField(max_length=350)
    sr21_5 = models.CharField(max_length=350)
    sr21_6 = models.CharField(max_length=350)
    sr21_7 = models.CharField(max_length=350)
    sr21_8 = models.CharField(max_length=350)
    sr21_9 = models.CharField(max_length=350)
    sr22_0 = models.CharField(max_length=350)
    sr22_1 = models.CharField(max_length=350)
    sr22_2 = models.CharField(max_length=350)
    sr22_3 = models.CharField(max_length=350)
    sr22_4 = models.CharField(max_length=350)
    sr22_5 = models.CharField(max_length=350)
    sr22_6 = models.CharField(max_length=350)
    sr22_7 = models.CharField(max_length=350)
    sr22_8 = models.CharField(max_length=350)
    sr22_9 = models.CharField(max_length=350)
    sr23_0 = models.CharField(max_length=350)
    sr23_1 = models.CharField(max_length=350)
    sr23_2 = models.CharField(max_length=350)
    sr23_3 = models.CharField(max_length=350)
    sr23_4 = models.CharField(max_length=350)
    sr23_5 = models.CharField(max_length=350)
    sr23_6 = models.CharField(max_length=350)
    sr23_7 = models.CharField(max_length=350)
    sr23_8 = models.CharField(max_length=350)
    sr23_9 = models.CharField(max_length=350)
    sr24_0 = models.CharField(max_length=350)
    sr24_1 = models.CharField(max_length=350)
    sr24_2 = models.CharField(max_length=350)
    sr24_3 = models.CharField(max_length=350)
    sr24_4 = models.CharField(max_length=350)
    sr24_5 = models.CharField(max_length=350)
    sr24_6 = models.CharField(max_length=350)
    sr24_7 = models.CharField(max_length=350)
    sr24_8 = models.CharField(max_length=350)
    sr24_9 = models.CharField(max_length=350)
    sr25_0 = models.CharField(max_length=350)
    sr25_1 = models.CharField(max_length=350)
    sr25_2 = models.CharField(max_length=350)
    sr25_3 = models.CharField(max_length=350)
    sr25_4 = models.CharField(max_length=350)
    sr25_5 = models.CharField(max_length=350)
    sr25_6 = models.CharField(max_length=350)
    sr25_7 = models.CharField(max_length=350)
    sr25_8 = models.CharField(max_length=350)
    select = models.CharField(max_length=350)
    legend_1 = models.CharField(max_length=350)
    legend_2 = models.CharField(max_length=350)
    legend_3 = models.CharField(max_length=350)
    legend_4 = models.CharField(max_length=350)
    legend_5 = models.CharField(max_length=350)
    legend_6 = models.CharField(max_length=350)
    legend_7 = models.CharField(max_length=350)
    legend_8 = models.CharField(max_length=350)
    legend_9 = models.CharField(max_length=350)
    legend_10 = models.CharField(max_length=350)
    legend_11 = models.CharField(max_length=350)
    edit_note = models.CharField(max_length=350)
    custom_legend = models.CharField(max_length=350)
    doc1 = models.CharField(max_length=350)
    doc2 = models.CharField(max_length=350)
    doc3 = models.CharField(max_length=350)
    analyzedby = models.ImageField(max_length=50)
    reviewedby = models.ImageField(max_length=50)
    approvedby = models.ImageField(max_length=50)    
    approvedby1 = models.ImageField(max_length=50,null=True)  
    location =models.CharField(max_length=50,null=True)  

    def __str__(self):
        return self.form_name +"-"+ self.lab_rep_no
    

class WasteWaterForm2(models.Model):
    form_name= "Waste Water Form"    
    id = models.AutoField(primary_key=True)
    lab_rep_no = models.CharField(max_length=50)
    invoice_no = models.CharField(max_length=50)
    repo_date = models.CharField(max_length=50)
    report_to = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    attention = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    sampleId = models.CharField(max_length=50)
    sample_Col_date = models.CharField(max_length=50)
    sample_desc = models.CharField(max_length=50)
    sampling_method = models.CharField(max_length=50)
    sample_type = models.CharField(max_length=50)
    sample_collected_by = models.CharField(max_length=50)
    date_of_analysis = models.CharField(max_length=50)
    test_description = models.CharField(max_length=50)
    select = models.CharField(max_length=50)
    result_1 = models.CharField(max_length=50)
    result_1_1 = models.CharField(max_length=50)
    result_2 = models.CharField(max_length=50)
    result_2_2 = models.CharField(max_length=50)
    result_3 = models.CharField(max_length=50)
    result_3_3 = models.CharField(max_length=50)
    result_4 = models.CharField(max_length=50)
    result_4_4 = models.CharField(max_length=50)
    result_5 = models.CharField(max_length=50)
    result_5_5 = models.CharField(max_length=50)
    result_6 = models.CharField(max_length=50)
    result_6_6 = models.CharField(max_length=50,null=True)
    result_7 = models.CharField(max_length=50,null=True)
    result_7_7 = models.CharField(max_length=50)
    metho_select = models.CharField(max_length=50)
    result_8 = models.CharField(max_length=50)
    result_8_8 = models.CharField(max_length=50)
    result_9 = models.CharField(max_length=50)
    result_9_9 = models.CharField(max_length=50)
    result_10 = models.CharField(max_length=50)
    result_10_10 = models.CharField(max_length=50)
    result_11 = models.CharField(max_length=50)
    result_11_11= models.CharField(max_length=50)
    result_12 = models.CharField(max_length=50)
    result_12_12 = models.CharField(max_length=50)
    result_13 = models.CharField(max_length=50)
    result_13_13 = models.CharField(max_length=50)
    result_14 = models.CharField(max_length=50)
    result_14_14 = models.CharField(max_length=50)
    result_15 = models.CharField(max_length=50)
    result_15_15 = models.CharField(max_length=50)
    result_16 = models.CharField(max_length=50)
    result_16_16 = models.CharField(max_length=50)
    result_17 = models.CharField(max_length=50)
    result_17_17 = models.CharField(max_length=50)
    result_18 = models.CharField(max_length=50)
    result_18_18 = models.CharField(max_length=50)
    result_19 = models.CharField(max_length=50)
    result_19_19 = models.CharField(max_length=50)
    result_20 = models.CharField(max_length=50)
    result_20_20 = models.CharField(max_length=50)
    result_21 = models.CharField(max_length=50)
    result_21_21 = models.CharField(max_length=50)
    result_22 = models.CharField(max_length=50)
    result_22_22 = models.CharField(max_length=50)
    result_23 = models.CharField(max_length=50)
    result_23_23 = models.CharField(max_length=50)
    result_24 = models.CharField(max_length=50)
    result_24_24 = models.CharField(max_length=50)
    result_25 = models.CharField(max_length=50)
    result_25_25 = models.CharField(max_length=50)
    result_26 = models.CharField(max_length=50)
    result_26_26 = models.CharField(max_length=50)
    result_27 = models.CharField(max_length=50)
    result_27_27 = models.CharField(max_length=50)
    result_28 = models.CharField(max_length=50)
    result_28_28 = models.CharField(max_length=50)
    result_29 = models.CharField(max_length=50)
    result_29_29 = models.CharField(max_length=50)
    result_30 = models.CharField(max_length=50)
    result_30_30 = models.CharField(max_length=50)
    result_31 = models.CharField(max_length=50)
    result_31_31 = models.CharField(max_length=50)
    result_32 = models.CharField(max_length=50)
    result_32_32 = models.CharField(max_length=50)
    legend_1 = models.CharField(max_length=50)
    legend_2 = models.CharField(max_length=50)
    legend_3 = models.CharField(max_length=50)
    legend_4 = models.CharField(max_length=50)
    legend_5 = models.CharField(max_length=50)
    legend_6 = models.CharField(max_length=50)
    legend_7 = models.CharField(max_length=50)
    legend_8 = models.CharField(max_length=50)
    legend_9 = models.CharField(max_length=50)
    legend_10 = models.CharField(max_length=50)
    legend_11 = models.CharField(max_length=50)
    editNote = models.CharField(max_length=50)
    customlegend = models.CharField(max_length=50)
    doc1 = models.CharField(max_length=50)
    doc2 = models.CharField(max_length=50)
    doc3 = models.CharField(max_length=50)
    analyzedby = models.ImageField(max_length=50)
    reviewedby = models.ImageField(max_length=50)
    approvedby = models.ImageField(max_length=50)
    approvedby1 = models.ImageField(max_length=50,null=True)
    location =models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.form_name
    

class NoiseAnalysis(models.Model):
    form_name = "Noise Analysis Form"  
    id = models.AutoField(primary_key=True)
    lab_rep_no = models.CharField(max_length=50)
    invoice_no = models.CharField(max_length=50)
    rep_date = models.CharField(max_length=50)
    report_to = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    attention = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    testId = models.CharField(max_length=50)
    test_perf_date = models.CharField(max_length=50)
    test_type = models.CharField(max_length=50)
    test_perf_by = models.CharField(max_length=50)
    test_desc = models.CharField(max_length=50)
    select1 = models.CharField(max_length=50,null=True)
    select = models.CharField(max_length=50,null=True)
    r1 = models.CharField(max_length=50)
    r1_1 = models.CharField(max_length=50)
    r2 = models.CharField(max_length=50)
    r2_2 = models.CharField(max_length=50)
    r3 = models.CharField(max_length=50)
    r3_3 = models.CharField(max_length=50)
    r4 = models.CharField(max_length=50)
    r4_4 = models.CharField(max_length=50)
    r5 = models.CharField(max_length=50)
    r5_5 = models.CharField(max_length=50)
    r6 = models.CharField(max_length=50)
    r6_6 = models.CharField(max_length=50)
    r7 = models.CharField(max_length=50)
    r7_7 = models.CharField(max_length=50)
    r8 = models.CharField(max_length=50)
    r8_8 = models.CharField(max_length=50)
    r9 = models.CharField(max_length=50)
    r9_9 = models.CharField(max_length=50)
    r10 = models.CharField(max_length=50)
    r10_10 = models.CharField(max_length=50)
    r11 = models.CharField(max_length=50)
    r11_11 = models.CharField(max_length=50)
    r12 = models.CharField(max_length=50)
    r12_12 = models.CharField(max_length=50)
    r13 = models.CharField(max_length=50)
    r13_13 = models.CharField(max_length=50)
    legend_1 = models.CharField(max_length=50)
    legend_2 = models.CharField(max_length=50)
    legend_3 = models.CharField(max_length=50)
    legend_4 = models.CharField(max_length=50)
    legend_5 = models.CharField(max_length=50)
    legend_6 = models.CharField(max_length=50)
    legend_7 = models.CharField(max_length=50)
    legend_8 = models.CharField(max_length=50)
    legend_9 = models.CharField(max_length=50)
    legend_10 = models.CharField(max_length=50)
    legend_11 = models.CharField(max_length=50)
    editNote = models.CharField(max_length=50)
    customlegend = models.CharField(max_length=50)
    doc1 = models.CharField(max_length=50)
    doc2 = models.CharField(max_length=50)
    doc3 = models.CharField(max_length=50)
    analyzedby = models.ImageField(max_length=50)
    reviewedby = models.ImageField(max_length=50)
    approvedby = models.ImageField(max_length=50)  
    approvedby1 = models.ImageField(max_length=50,null=True)  
    location =models.CharField(max_length=50,null=True)


    def __str__(self):
        return self.form_name
    

